blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://discord.com/invite/rBTTVJp
    about: This issue tracker is not for support questions. Please refer to the Appsmith community's help and discussion forums.
